services:
  - type: web
    name: patient-api
    env: docker
    branch: main
    dockerfilePath: ./Dockerfile
    plan: free

    envVars:
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:${PORT}
      - key: ConnectionStrings__Default
        value: Data Source=/tmp/patient.db
