services:
  - type: web
    name: patient-api
    runtime: dotnet8
    branch: main
    buildCommand: dotnet restore && dotnet publish -c Release -o out
    startCommand: dotnet out/PatientApi.dll
    envVars:
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:${PORT}
      - key: ConnectionStrings__Default
        value: Data Source=/data/patient.db
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
